services:
  - type: web
    name: diisco-backend
    env: python
    region: frankfurt
    plan: free
    branch: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        sync: false
